### ISSUE TITLE
Registration Page User Story

### ISSUE THREAD

**Issue by amyrosen** [ArdentMC/openFDA-Prototype#1]
As a user I would like a registration page with the ability to sign up.
I will accept this user story with the following acceptance criteria:
1. Email Address: allows me to enter my email address 
2. Password field: allows me to create a password
3. After I have registered I get an email

**Comment by JCorrell** [comment]
Let's leave out username field.  Email address is the username.

**Comment by amyrosen** [comment]
Ok it has been updated.

**Comment by amyrosen** [comment]
Justin I assigned this to you but we can change this if someone else has started on it or you have too much. We'll discuss in our update meeting today.
