### ISSUE TITLE
Create Map Incident Module

### ISSUE THREAD

**Issue by amyrosen** [ArdentMC/openFDA-Prototype#14]
This module will display a map with the incidents on the map

**Comment by amyrosen** [comment]
Justin close this out when you are complete with the map or let me know and I will

**Comment by justindowns** [comment]
Amy, ready to close after verifying next deployment

**Comment by amyrosen** [comment]
I can see the map I am closing this out. I will add issues/bugs on anything that we have time to fix or change.
