### ISSUE TITLE
Create ArdentMC email address

### ISSUE THREAD

**Issue by amyrosen** [ArdentMC/openFDA-Prototype#17]
Work with IT to get email address created for use.

**Comment by Kindafearless** [comment]
I have submitted a ticket (#DKY-909-56383) with helpdesk to create a @ardentmc email address.

**Comment by JCorrell** [comment]
We have a few available to us.

Josh, can you help?

On Jun 22, 2015 10:02 AM, Elise Walker <notifications@github.com> wrote:
I have submitted a ticket (#DKY-909-56383) with helpdesk to create a @ardentmc email address.

---

**Comment by Kindafearless** [comment]
openfda@ardentmc.com created.
