### ISSUE TITLE
Create URL and submit to government user story

### ISSUE THREAD

**Issue by amyrosen** [ArdentMC/openFDA-Prototype#2]
Come up with a name and create URL.
Acceptance criteria:
1. I will accept this user story when a name has been determined and a URL has been created for prototype to be published to. 
2. I will accept this user story when the URL can be publically available and at the top of a README.md file located in the root directory of the repository. 
3. I will accept this user story when the URL can be accessed Via the Publically available URL at the top of the README.md file without generating any HTTP 4xx or 5xx errors.

**Comment by Kindafearless** [comment]
The URL ardentmc18f is what we have currently. It's not very catchy, but I'll go ahead and use that until we commit to it or find something better.

**Comment by Kindafearless** [comment]
This is pending on picking a new exciting name right?

**Comment by Kindafearless** [comment]
The current suggestions on the board are:

ChuckItOut
WiredCupboard
NoshAlert
FoodWise
FoodAdvisor
ProvisionAdvisor
FoodSOS
FoodAssistance
FoodWatch
FoodWatcher
FoodAlert
Food911
NoshAlert
WatchfulFood
FoodOnTheMove

**Comment by Kindafearless** [comment]
My favorites are:

* ChuckItOut
* WiredCupboard
* NoshAlert
* FoodAdvisor

**Comment by amyrosen** [comment]
Yes or until we get a response from Jim?

**Comment by JCorrell** [comment]
Yes ma'am
________________________________

**Comment by Kindafearless** [comment]
So based on Jim and Amy's feedback, **NoshAlert**? I personally dig it :)

**Comment by amyrosen** [comment]
Do it up!

**Comment by JCorrell** [comment]
NoshAlert wins!

http://www.noshalert.com
