### ISSUE TITLE
No map

### ISSUE THREAD

**Issue by brandonlabonte** [ArdentMC/openFDA-Prototype#30]
I signed up and logged in about one hour ago, and didn't see any data reported (map or data).

**Comment by amyrosen** [comment]
When you sign up on the first screen under Food (for now this will be changing) you should see a link "food recalls" that you can click on. That should bring you to a page where you can search. Jan - April is a good one and select California. It should display a map with some information about recalls but we are still working on this.

**Comment by amyrosen** [comment]
Some things are not working perfectly yet so we'll be looking at this for sure.
