### ISSUE TITLE
Search not working 

### ISSUE THREAD

**Issue by amyrosen** [ArdentMC/openFDA-Prototype#31]
When I add the state i want to look for alerts in from the welcome page once i get to the next screen with the food alerts and the map the same 2 states are highlighted (Oregon and Washington) but i entered California which also shows there is a food alert. Also if i change my search criteria its not refreshing.

**Comment by amyrosen** [comment]
Gene I know you are not done with this yet I have seen changes more states show up in the search I think the state that you select should just show up if there is no information for that state perhaps a message comes back saying no results were returned for that state - also besides choosing a state maybe add one more selection that the user can select all states and then the results show as they have.

**Comment by IslandWalker** [comment]
Done, the highlight were the issue.
