### ISSUE TITLE
Social Media logins not functional yet

### ISSUE THREAD

**Issue by amyrosen** [ArdentMC/openFDA-Prototype#32]
I tested facebook login it doesn't seem to be working. It was working at one point. Jim and Bryan were having issues with it.

**Comment by justindowns** [comment]
Facebook, Google+, and LinkedIn working

**Comment by JCorrell** [comment]
Disagree.

This is the issue I get with Facebook:

![image](https://cloud.githubusercontent.com/assets/1693201/8379604/26aff650-1bef-11e5-8760-10c21df49db3.png)

**Comment by amyrosen** [comment]
I'll test it out

**Comment by Kindafearless** [comment]
I'm also seeing that result on both:
http://kubernetes-master.cloudapp.net/
and
http://www.ardentmc18f.com/

**Comment by Kindafearless** [comment]
LinkedIn appears to be working on both sites.

**Comment by Kindafearless** [comment]
Google+ is working on Kubernetes-master, but not ardentmc18f

**Comment by justindowns** [comment]
Try clearing your cache, it works...
https://www.youtube.com/watch?v=n31GBOJU-Ng&feature=youtu.be

**Comment by Kindafearless** [comment]
It didn't work for me. Sorry.

**Comment by JCorrell** [comment]
Nor for me.

Remember that we're not developing this for ourselves, but for users and evaluators whom we won't require to refresh their cache.

At tho point, I think we should consider scrapping tho capability unless we think we very close to a real solution that doesn't require a workaround.

Don't take it personally. We just have a working solution with custom logins and I think I'd rather see better design implemented and a more personalized experience  (ie, alerts based on foods user cares about).

Jim




Sent from my Windows Phone
________________________________

**Comment by Kindafearless** [comment]
So we definitely did have a mongo problem, I can confirm. The new configuration should fix the google+ social media problem.

I can confirm that google+ and linkedin are now working for me. Maybe we only need to off facebook?

**Comment by justindowns** [comment]
Approval from Facebook still pending.  If not received by tomorrow I will remove Facebook link.

**Comment by JCorrell** [comment]
also add redirects for noshalert.com

**Comment by justindowns** [comment]
Facebook approval received and noshalert.com has been added for all 3 social media login options.  Other users please verify before closing.

**Comment by amyrosen** [comment]
This is working just waiting to bring back the icons and test them out that way and then we can close this issue for good

**Comment by amyrosen** [comment]
Tested this morning again with the new application and its working I am closing this out.
