### ISSUE TITLE
Install Linux On Azure User Story

### ISSUE THREAD

**Issue by amyrosen** [ArdentMC/openFDA-Prototype#4]
As a product owner I would like Linux installed on Azure for everyone to use.

**Comment by Kindafearless** [comment]
Azure is up and running and I've created Kubernetes cluster to deploy docker containers to as "pods". Opening new stories to account for the rest of the work.

**Comment by brandonlabonte** [comment]
It’s like you are talking in a different language.  I’m pretty sure I’ve never heard the word “Kubernetes"

---
Brandon LaBonte | President & CEO | ArdentMC
Headquarters – Reston, VA
SBA-Certified HUBZone Firm
703.964.8011 | Direct
www.ardentmc.com<http://www.ardentmc.com/>

From: Elise Walker
Reply-To: ArdentMC/openFDA-Prototype
Date: Monday, June 22, 2015 at 12:18 AM
To: ArdentMC/openFDA-Prototype
Subject: Re: [openFDA-Prototype] Install Linux On Azure User Story (#4)


Azure is up and running and I've created Kubernetes cluster to deploy docker containers to as "pods". Opening new stories to account for the rest of the work.

—
Reply to this email directly or view it on GitHub<https://github.com/ArdentMC/openFDA-Prototype/issues/4#issuecomment-113996986>.

________________________________

This email and any files transmitted with it may contain confidential, sensitive, and/or proprietary information which is exempt from disclosure under applicable law (Computer Fraud and Abuse Act of 1986 (18 USC 1030) and The Privacy Act, (5 USC 552). It is meant solely for the intended recipient. If you are not the intended recipient, any disclosure, copying, distribution, or any action taken or omitted in reliance on this, is prohibited and may be unlawful. If you received this message in error, please notify the sender immediately and delete the material in its entirety.

**Comment by amyrosen** [comment]
http://kubernetes.io/
