### ISSUE TITLE
Research monitoring tool user story

### ISSUE THREAD

**Issue by amyrosen** [ArdentMC/openFDA-Prototype#5]
as a product owner I would like research conducted regarding monitoring tools one of the items Elise brought up was Duckboard.

**Comment by JCorrell** [comment]
Looks like Duckboard is out, as suspected...current investigation is a lot of software I'm unfamiliar with.

**Comment by justindowns** [comment]
key created for my email and requests tested

**Comment by justindowns** [comment]
committed web app that includes registration and modules for food and medication alerts

**Comment by Kindafearless** [comment]
In progress of spinning up full fledged cluster still. But the first monitoring tool is available:
Heapster: https://130.211.126.71/api/v1beta3/proxy/namespaces/default/services/monitoring-heapster/
username: admin
password: 858Clc5AfQRuRUwt

**Comment by Kindafearless** [comment]
Forgive the last url being broken. To make up for it, here is jenkins using our new dns.

http://jenkins.ardentmc18f.com:8080/

**Comment by amyrosen** [comment]
This looks nice
