### ISSUE TITLE
Date Selector

### ISSUE THREAD

**Issue by amyrosen** [ArdentMC/openFDA-Prototype#53]
When I put try to put a date in for the future in the correct format, it accepts it and turns green. But when I try to submit it just shows a circle with an X and I have no idea what's wrong. - Recommend not allowing users to put in future dates and let the user know they have entered a date that has not occurred yet.

**Comment by IslandWalker** [comment]
added extra validation so that min and max dates are not exceeded.

**Comment by amyrosen** [comment]
Tested it looks good.
