### ISSUE TITLE
Add Login Redirects

### ISSUE THREAD

**Issue by JCorrell** [ArdentMC/openFDA-Prototype#61]
For

noshalert.com
noshalert.me
noshalert.info

**Comment by IslandWalker** [comment]
Since it’s an information application…:    Noshalert.info

Eugene t. staten ii | SOFTWARE ENGINEER - Lead technology consultant | ArdentMC
Maui Software Development Center
SBA-Certified HUBZone Firm
808.757.9808 | Main
                 9831 | Extension

**Comment by IslandWalker** [comment]
Redirects are there.

**Comment by amyrosen** [comment]
The 2013 winner of this proposal was this site:

http://www.iodine.com/


They used .com
Not sure that matters but they too were an information site.
