### ISSUE TITLE
Replace Landing Page Verbiage

### ISSUE THREAD

**Issue by JCorrell** [ArdentMC/openFDA-Prototype#63]
**Replace**

This a quote prototype for a client to the Open FDA Api web service.

This application allows users to...
• Search the Open FDA Api for Food Enforcement Recalls that took place in a specified state for a user supplied, range of dates. 

Food 

View reports of food recalls.

** With **

NoshAlert is your resource for discovering food-related incidents reported in your area and around the country.

See my food alerts now!  *<-- this is new link to map search page *

**Comment by IslandWalker** [comment]
Please take a look.  If you like it, we can close this.

**Comment by amyrosen** [comment]
Jim please answer Gene's question.
